{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "pbuf-registry.fullname" . }}-postgresql
  labels:
    helm.sh/chart: {{ include "pbuf-registry.chart" $ }}
    {{- if $.Chart.AppVersion }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "pbuf-registry.name" $ }}-postgresql
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: database
spec:
  serviceName: {{ include "pbuf-registry.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: {{ $.Release.Service }}
      app.kubernetes.io/name: {{ include "pbuf-registry.name" $ }}-postgresql
      app.kubernetes.io/instance: {{ $.Release.Name }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/name: {{ include "pbuf-registry.name" $ }}-postgresql
        app.kubernetes.io/instance: {{ $.Release.Name }}
        app.kubernetes.io/component: database
    spec:
      {{- with .Values.postgresql.primary.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: postgresql
          image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
          imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
          {{- with .Values.postgresql.primary.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: POSTGRES_USER
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "pbuf-registry.fullname" . }}-postgresql
                  key: postgres-password
            - name: POSTGRES_DB
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - name: postgresql
              containerPort: 5432
              protocol: TCP
          {{- if .Values.postgresql.primary.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgresql.auth.username }} -d {{ .Values.postgresql.auth.database }}
            initialDelaySeconds: {{ .Values.postgresql.primary.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgresql.primary.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.postgresql.primary.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.postgresql.primary.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.postgresql.primary.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.postgresql.primary.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - pg_isready -U {{ .Values.postgresql.auth.username }} -d {{ .Values.postgresql.auth.database }}
            initialDelaySeconds: {{ .Values.postgresql.primary.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.postgresql.primary.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.postgresql.primary.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.postgresql.primary.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.postgresql.primary.readinessProbe.successThreshold }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          {{- with .Values.postgresql.primary.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- if not .Values.postgresql.primary.persistence.enabled }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
  {{- if .Values.postgresql.primary.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        {{- if .Values.postgresql.primary.persistence.storageClass }}
        storageClassName: {{ .Values.postgresql.primary.persistence.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.primary.persistence.size | quote }}
  {{- end }}
{{- end }}
