{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pbuf-registry.fullname" . }}-postgresql
  labels:
    {{- include "pbuf-registry.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    {{- include "pbuf-registry.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}
