{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pbuf-registry.fullname" . }}-postgresql
  labels:
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: {{ include "pbuf-registry.name" $ }}-postgresql
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: postgresql
      port: 5432
      targetPort: postgresql
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "pbuf-registry.name" $ }}-postgresql
    app.kubernetes.io/component: database
{{- end }}
