{{- if and .Values.secrets.create (not .Values.secrets.eso.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pbuf-registry.fullname" . }}
type: Opaque
data:
{{- if .Values.secrets.databaseDSN }}
  DATA_DATABASE_DSN: {{ .Values.secrets.databaseDSN | b64enc | quote }}
{{- end }}
{{- end }}