{{- if and .Values.secrets.create (not .Values.secrets.eso.create) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pbuf-registry.fullname" . }}
type: Opaque
data:
{{- if .Values.secrets.databaseDSN }}
  DATA_DATABASE_DSN: {{ .Values.secrets.databaseDSN | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.staticToken }}
  SERVER_STATIC_TOKEN: {{ .Values.secrets.staticToken | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.grpcTlsCert }}
  server-cert.pem: {{ .Values.secrets.grpcTlsCert | b64enc | quote }}
{{- end }}
{{- if .Values.secrets.grpcTlsKey }}
  server-key.pem: {{ .Values.secrets.grpcTlsKey | b64enc | quote }}
{{- end }}
{{- end }}